sudo: false
language: csharp
solution: RiichiSharp.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore RiichiSharp.sln
after_script:
  - nunit-console RiichiSharp.Tests/bin/Release/RiichiSharp.Tests.dll